export const ADD_TOTAL_IRREGULAR_VERBS = 'TOTAL_IRREGULAR_VERBS';
export const INCREMENT_CORRECT_IRREGULAR_VERB = 'INCREMENT_CORRECT_IRREGULAR_VERB';
export const ADD_INCORRECT_IRREGULAR_VERB = 'ADD_INCORRECT_IRREGULAR_VERB';